### ISSUE TITLE
Build trino:373 image

### ISSUE THREAD

**Issue by erikerlandson** [opendatahub-io/odh-images#14]
see https://github.com/operate-first/apps/issues/1843
cc @rimolive

**Comment by erikerlandson** [comment]
On a meta-note, it may be good to build these images as trino releases them, if it's not a lot of effort.  The trino community seems to be iterating fairly rapidly (they're already on 375), and some of their work intersects features or bug fixes have impacted us.

**Comment by anishasthana** [comment]
It's usually not a lot of effort, but just needs someone to keep an eye on things. We always welcome contributions :-)

**Comment by erikerlandson** [comment]
how do you manage the trino image builds now?  Is it a pull request I can submit that bumps the trino version?

**Comment by anishasthana** [comment]
Admittedly I haven't built the image myself, but it looks like just a basic bump + confirmation of image functionality: https://github.com/opendatahub-io/odh-images/blob/main/trino/Dockerfile#L1.
Once the image is updated and built, we'll need a corresponding PR to odh-manifests to bump the Trino image version being used.

**Comment by erikerlandson** [comment]
I think I see where this can be modified - I doubt I have permissions to push to `quay.io/opendatahub`

**Comment by erikerlandson** [comment]
I pushed to `quay.io/os-climate/trino:373`

**Comment by mqhackett** [comment]
@anishasthana @erikerlandson  Here is an attempt at the corresponding PR to odh-manifests to bump the Trino image version being used --->>> 

https://github.com/opendatahub-io/odh-manifests/pull/553

**Comment by erikerlandson** [comment]
I have a system for this now, I'll close this issue
