### ISSUE TITLE
Include Apache Hive v2 metastore image

### ISSUE THREAD

**Issue by shawnzhu** [opendatahub-io/odh-images#2]
I saw it uses a UBI image for Hive metastore v2 in ODH: https://github.com/opendatahub-io/odh-manifests/blob/e6a4f42a690293ecda356ca936d069baf1bb3ce5/trino/base/hive-metastore-dc.yaml#L81

but I can not find where its manifest is to patch/upgrade.

If you don't mind, I'd happy to contribute code of this repo back https://github.com/IBM/docker-hive with:
* UBI image
* build/testing process via skaffold

**Comment by rimolive** [comment]
@shawnzhu The manifest for this image is in this repo: https://github.com/RedHatInsights/ubi-trino. We are working with this team to have hive and trino images, but we didn't decide if we keep the manifests in their repos or if we move here.

**Comment by rimolive** [comment]
Sorry, I sent the github repo for trino image. The hive image is in this repo: https://github.com/RedHatInsights/ubi-hive

**Comment by shawnzhu** [comment]
@rimolive thank you! I will follow up in repo https://github.com/RedHatInsights/ubi-hive
